"""creation des 22 tables

Revision ID: 8073084cc40c
Revises: 
Create Date: 2026-06-13 13:31:19.671066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8073084cc40c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories_depenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('moyens_paiement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('libelle', sa.String(length=50), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('parametres_systeme',
    sa.Column('cle', sa.String(length=100), nullable=False),
    sa.Column('valeur', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cle')
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('systeme', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('types_abonnements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('duree_jours', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('avantages', sa.String(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('utilisateurs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('derniere_connexion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero_membre', sa.String(length=30), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('sexe', sa.String(length=10), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('numero_piece_identite', sa.String(length=50), nullable=True),
    sa.Column('contact_urgence_nom', sa.String(length=100), nullable=True),
    sa.Column('contact_urgence_telephone', sa.String(length=20), nullable=True),
    sa.Column('groupe_sanguin', sa.String(length=5), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_membre')
    )
    op.create_table('depenses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('categorie_id', sa.UUID(), nullable=False),
    sa.Column('libelle', sa.String(length=200), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_depense', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('justificatif_url', sa.String(), nullable=True),
    sa.Column('valide_par', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['categorie_id'], ['categories_depenses.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['valide_par'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('employes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('fonction', sa.String(length=50), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('adresse', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('date_embauche', sa.Date(), nullable=False),
    sa.Column('type_contrat', sa.String(length=30), nullable=True),
    sa.Column('salaire_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_audit',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('cible_table', sa.String(length=50), nullable=True),
    sa.Column('cible_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('adresse_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journal_caisse',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('date_jour', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('total_encaisse', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_depenses', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('solde', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cloture_par', sa.UUID(), nullable=True),
    sa.Column('cloture_le', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cloture_par'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date_jour')
    )
    op.create_table('abonnements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('type_abonnement_id', sa.UUID(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('renouvele_de', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['renouvele_de'], ['abonnements.id'], ),
    sa.ForeignKeyConstraint(['type_abonnement_id'], ['types_abonnements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fiches_paie',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('employe_id', sa.UUID(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('salaire_base', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('primes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('bonus', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('retenues', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('salaire_final', sa.Numeric(precision=10, scale=2),
          sa.Computed('salaire_base + primes + bonus - retenues', persisted=True),
          nullable=True),
    sa.Column('statut_paiement', sa.String(length=20), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=True),
    sa.Column('fiche_pdf_url', sa.String(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employe_id', 'mois', 'annee', name='uq_fiche_paie_periode')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('destinataire_type', sa.String(length=20), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('employe_id', sa.UUID(), nullable=True),
    sa.Column('numero_telephone', sa.String(length=20), nullable=False),
    sa.Column('canal', sa.String(length=10), nullable=False),
    sa.Column('type_notification', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('provider_message_id', sa.String(length=100), nullable=True),
    sa.Column('fallback_sms_envoye', sa.Boolean(), nullable=False),
    sa.Column('date_envoi', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['employe_id'], ['employes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planning_coachs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('titre', sa.String(length=150), nullable=False),
    sa.Column('date_seance', sa.Date(), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=False),
    sa.Column('heure_fin', sa.Time(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['employes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('methode', sa.String(length=20), nullable=False),
    sa.Column('heure_entree', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('heure_sortie', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duree_minutes', sa.Integer(), nullable=True),
    sa.Column('enregistre_par', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['enregistre_par'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programmes_sportifs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(length=150), nullable=False),
    sa.Column('objectif', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['coach_id'], ['employes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seances_journalieres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('nom_client_occasionnel', sa.String(length=150), nullable=True),
    sa.Column('date_seance', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('encaisse_par', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['encaisse_par'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartes_membres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=False),
    sa.Column('abonnement_id', sa.UUID(), nullable=True),
    sa.Column('qr_code_uuid', sa.UUID(), nullable=False),
    sa.Column('qr_code_url', sa.String(), nullable=True),
    sa.Column('date_generation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_expiration', sa.Date(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['abonnement_id'], ['abonnements.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code_uuid')
    )
    op.create_table('paiements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('abonnement_id', sa.UUID(), nullable=True),
    sa.Column('seance_journaliere_id', sa.UUID(), nullable=True),
    sa.Column('type_paiement', sa.String(length=30), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('moyen_paiement_id', sa.UUID(), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.Column('facture_pdf_url', sa.String(), nullable=True),
    sa.Column('recu_pdf_url', sa.String(), nullable=True),
    sa.Column('encaisse_par', sa.UUID(), nullable=False),
    sa.Column('date_paiement', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['abonnement_id'], ['abonnements.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['encaisse_par'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['moyen_paiement_id'], ['moyens_paiement.id'], ),
    sa.ForeignKeyConstraint(['seance_journaliere_id'], ['seances_journalieres.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paiements')
    op.drop_table('cartes_membres')
    op.drop_table('seances_journalieres')
    op.drop_table('programmes_sportifs')
    op.drop_table('presences')
    op.drop_table('planning_coachs')
    op.drop_table('notifications')
    op.drop_table('fiches_paie')
    op.drop_table('abonnements')
    op.drop_table('journal_caisse')
    op.drop_table('journal_audit')
    op.drop_table('employes')
    op.drop_table('depenses')
    op.drop_table('clients')
    op.drop_table('utilisateurs')
    op.drop_table('role_permissions')
    op.drop_table('types_abonnements')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('parametres_systeme')
    op.drop_table('moyens_paiement')
    op.drop_table('categories_depenses')
    # ### end Alembic commands ###
