"""tarifs total fitness - sexe et montant inscription

Revision ID: d9ed3f484f67
Revises: 8073084cc40c
Create Date: 2026-06-13 13:50:36.310734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9ed3f484f67'
down_revision: Union[str, Sequence[str], None] = '8073084cc40c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('abonnements', sa.Column('est_inscription', sa.Boolean(), nullable=False))
    op.add_column('types_abonnements', sa.Column('sexe', sa.String(length=10), nullable=True))
    op.add_column('types_abonnements', sa.Column('montant_inscription', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('types_abonnements', 'montant_inscription')
    op.drop_column('types_abonnements', 'sexe')
    op.drop_column('abonnements', 'est_inscription')
    # ### end Alembic commands ###
